openapi: 3.0.0
info:
  title: proyek3
  version: 1.0.0
servers:
  - url: http://localhost:8081
  - url: https://be-3.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
tags:
  - name: auth
  - name: payment
  - name: custom
  - name: user
paths:
  /api/register:
    post:
      tags:
        - auth
      summary: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: patir
                email: ehtir57@gmail.com
                password: siganteng
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/login:
    post:
      tags:
        - auth
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: ehtir57@gmail.com
                password: siganteng
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/protected/tambah-emas:
    post:
      tags:
        - auth
      summary: post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: emas 10000 gram
                karatan: 100
                berat: 19
                harga: 150000500
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /protected/emas:
    get:
      tags:
        - auth
      summary: get all
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /protected/emas/update/:
    put:
      tags:
        - auth
      summary: New Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: emas 1 gram
                karatan: 100
                berat: 19
                harga: 150000500
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment:
    post:
      tags:
        - payment
      summary: payment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                gross_amount: 5000000
                customer_details:
                  name: Fathir
                  email: fathir080604@gmail.com
                  phone: '08953319342686'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders:
    get:
      tags:
        - custom
      summary: Get All Order
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - custom
      summary: Add Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                jenis_perhiasan: Anting
                jenis_emas: Emas 21K
                berat_emas: 10.5
                campuran_tambahan: Palladium
                persentase_emas: 90
                total_harga: 45633223
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}:
    get:
      tags:
        - custom
      summary: Get by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users:
    get:
      tags:
        - user
      summary: Get All
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/protected/users/105:
    get:
      tags:
        - user
      summary: User By ID
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/protected/users:
    post:
      tags:
        - user
      summary: Add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: John Doe
                email: johndoe@example.com
                password: SecurePass123
                verified: true
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/protected/users/108:
    put:
      tags:
        - user
      summary: Update User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Jane Doe
                email: janedoe@example.com
                password: newpassword123
                verified: true
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - user
      summary: New Request
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}